### ISSUE TITLE
Error after  unmuting 

### ISSUE THREAD

**Issue by brewston** [rhasspy/wyoming-satellite#10]
I had the satellite muted for a few hours, when I un-muted I saw : 

`Dec 14 16:44:43 raspberrypi run[3159]: ERROR:asyncio:Task exception was never retrieved
Dec 14 16:44:43 raspberrypi run[3159]: future: <Task finished name='Task-11' coro=<AsyncEventHandler.run() done, defined at /home/pi/wyoming-satellite/.venv/lib/python3.11/site-packages/wyoming/server.py:28> exception=ConnectionResetError(104, 'Connection reset by peer')>
Dec 14 16:44:43 raspberrypi run[3159]: Traceback (most recent call last):
Dec 14 16:44:43 raspberrypi run[3159]:   File "/home/pi/wyoming-satellite/wyoming_satellite/satellite.py", line 128, in event_to_server
Dec 14 16:44:43 raspberrypi run[3159]:     await async_write_event(event, self._writer)
Dec 14 16:44:43 raspberrypi run[3159]:   File "/home/pi/wyoming-satellite/.venv/lib/python3.11/site-packages/wyoming/event.py", line 129, in async_write_event
Dec 14 16:44:43 raspberrypi run[3159]:     await writer.drain()
Dec 14 16:44:43 raspberrypi run[3159]:   File "/usr/lib/python3.11/asyncio/streams.py", line 378, in drain
Dec 14 16:44:43 raspberrypi run[3159]:     await self._protocol._drain_helper()
Dec 14 16:44:43 raspberrypi run[3159]:   File "/usr/lib/python3.11/asyncio/streams.py", line 173, in _drain_helper
Dec 14 16:44:43 raspberrypi run[3159]:     await waiter
Dec 14 16:44:43 raspberrypi run[3159]:   File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
Dec 14 16:44:43 raspberrypi run[3159]:     data = self._sock.recv(self.max_size)
Dec 14 16:44:43 raspberrypi run[3159]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 16:44:43 raspberrypi run[3159]: ConnectionResetError: [Errno 104] Connection reset by peer
Dec 14 16:44:43 raspberrypi run[3164]: overrun!!! (at least 7742945.297 ms long)
`

**Comment by GeorgeR** [comment]
Same here
