### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by ignacio82** [rhasspy/wyoming-satellite#134]
My satellite was working fine but now is failing to start. This is how I run it (i have not change anything):

```
ignacio@pi-satellite:~ $ /home/ignacio/wyoming-satellite/script/run --name 'wyoming living room' \
  --uri 'tcp://0.0.0.0:10700' \
  --wake-uri 'tcp://127.0.0.1:10401' \
  --wake-word-name 'Dumbledore' \
  --mic-command 'parecord --property=media.role=phone --rate=16000 --channels=1 --format=s16le --raw --latency-msec 10' \
  --snd-command 'paplay --property=media.role=announce --rate=44100 --channels=1 --format=s16le --raw --latency-msec 10' \
  --snd-command-rate 44100 \
  --detection-command '/home/ignacio/wyoming-enhancements/snapcast/scripts/awake.sh' \
  --tts-stop-command '/home/ignacio/wyoming-enhancements/snapcast/scripts/done.sh' \
  --mic-auto-gain 5 \
  --mic-noise-suppression 2 \
  --event-uri 'tcp://127.0.0.1:10500'
/home/ignacio/wyoming-satellite/.venv/bin/python3: No module named wyoming_satellite
Traceback (most recent call last):
  File "/home/ignacio/wyoming-satellite/script/run", line 12, in <module>
    subprocess.check_call([context.env_exe, "-m", "wyoming_satellite"] + sys.argv[1:])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ignacio/wyoming-satellite/.venv/bin/python3', '-m', 'wyoming_satellite', '--name', 'wyoming living room', '--uri', 'tcp://0.0.0.0:10700', '--wake-uri', 'tcp://127.0.0.1:10401', '--wake-word-name', 'Dumbledore', '--mic-command', 'parecord --property=media.role=phone --rate=16000 --channels=1 --format=s16le --raw --latency-msec 10', '--snd-command', 'paplay --property=media.role=announce --rate=44100 --channels=1 --format=s16le --raw --latency-msec 10', '--snd-command-rate', '44100', '--detection-command', '/home/ignacio/wyoming-enhancements/snapcast/scripts/awake.sh', '--tts-stop-command', '/home/ignacio/wyoming-enhancements/snapcast/scripts/done.sh', '--mic-auto-gain', '5', '--mic-noise-suppression', '2', '--event-uri', 'tcp://127.0.0.1:10500']' returned non-zero exit status 1.
```

Any suggestion to fix this would be much appreciated.

**Comment by ignacio82** [comment]
reinstalling solved the problem. No clue what caused it. I hope a docker version of this (ideally with pulse audio) gets released soon.
