### ISSUE TITLE
Error - Wakeword install

### ISSUE THREAD

**Issue by smartypants1138** [rhasspy/wyoming-satellite#170]
Hello - 

I'm continually hitting this error at the Wakeword install step, see screenshot. 

ERROR: Could not find a version that satisfies the requirement tflite-runtime-nightly (from versions: none)
ERROR: No matching distribution found for tflite-runtime-nightly
![image](https://github.com/rhasspy/wyoming-satellite/assets/40124396/a252a619-4d9c-43eb-a858-97bca82b766e)

Thanks in advance for any advice!

**Comment by LiveForToday** [comment]
I ran into this. what worked for me was I ran and apt-get update, rebooted, then  run python or python3 -m installer. make simple changes and apply it. then try and run the script/setup again. I believe this is what got me working. I had a lot of trial an error but this might work for you as well. Hopefully it will.

**Comment by tannisroot** [comment]
Try following the instructions again but in the beginning, instead of flashing "Legacy" Raspberry Pi OS, select the same variant but the normal, latest non-legacy one. So something like "Raspberry Pi OS 64-bit Lite".

**Comment by tsx-5** [comment]
Did starting over and using a different OS solve the problem?  I'm running into it as well...

**Comment by tannisroot** [comment]
> Did starting over and using a different OS solve the problem? I'm running into it as well...

It did for me. I having a Pi Zero 2W with a 2-Mic hat and everything works fine under non-legacy Pi OS.

**Comment by tsx-5** [comment]
Which version did you use?  If I may ask...

**Comment by tannisroot** [comment]
> Which version did you use? If I may ask...

![image](https://github.com/rhasspy/wyoming-satellite/assets/10602045/280538c9-1c0d-4c84-94c6-7c2669d1d2a6)

**Comment by tsx-5** [comment]
Thanks for that.  Not sure what's going on - my attempts always causes the Pi to lockup when it's trying to create the drivers :-/

**Comment by tannisroot** [comment]
> Thanks for that. Not sure what's going on - my attempts always causes the Pi to lockup when it's trying to create the drivers :-/

What Pi model is it?

**Comment by tsx-5** [comment]
Raspberry Pi Zero 2 W

**Comment by smartypants1138** [comment]
@tannisroot, thank you, I tried the non-legacy version and it locks up as @tsx-5 describes. I'm using Pi Zero 2W

**Comment by tannisroot** [comment]
This is so weird. How can I have the exact same hardware and not have this issue under the exact same OS?

**Comment by tannisroot** [comment]
This is so weird. How can have the exact same hardware and not have this issue under the exact same OS?

**Comment by smartypants1138** [comment]
Yeah, agreed! Really odd. 

I found this and I was able to complete the install: 

[https://github.com/rhasspy/wyoming-satellite/issues/157#issuecomment-2067548218](url)

**Comment by smartypants1138** [comment]
I should also mention - I went back to the legacy RPi install and I do have wake word working, but no LED yet.

**Comment by tannisroot** [comment]
> > Thanks for that. Not sure what's going on - my attempts always causes the Pi to lockup when it's trying to create the drivers :-/
> 
> What Pi model is it?

When you say `creating drivers`, do you mean when it compiles? Or when it tries to install them after compilation?
It's possible for whatever reason that the Pi is consuming more power during compile under bookworm, and due to a bad power supply it locks up.

**Comment by holgerb** [comment]
I got the same problem, used the legacy rpiOS and were not able to install the wakeword. Follow the hin to retry it using the "non legacy" lite version but then stuck during the driver compilation an 

```bash
Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.6.20+rpt-rpi-v8 -C /lib/modules/6.6.20+rpt-rpi-v8/build M=/var/lib/dkms/seeed-voicecard/0.3/build..
````

After running htop in parallel the zero got stuck when the swap was used about 99%. 

Increasing the swap to 512mb following [this guide ](https://pimylifeup.com/raspberry-pi-swap-file/) solved it for me.

**Comment by tsx-5** [comment]
Thanks holgerb,

Increasing the swap allowed for everything to compile and move forward.  That said, wakeword still seems to have an issue...
```

● wyoming-openwakeword.service - Wyoming openWakeWord
     Loaded: loaded (/etc/systemd/system/wyoming-openwakeword.service; disabled; preset: enabled)
     Active: active (running) since Fri 2024-06-07 18:16:37 EDT; 1min 11s ago
   Main PID: 883 (python3)
      Tasks: 9 (limit: 174)
        CPU: 5.604s
     CGroup: /system.slice/wyoming-openwakeword.service
             ├─883 python3 /home/bat-sat/wyoming-openwakeword/script/run --uri tcp://127.0.0.1:10400
             └─884 /home/bat-sat/wyoming-openwakeword/.venv/bin/python3 -m wyoming_openwakeword --uri tcp://127.0.0.1:10400

Jun 07 18:16:37 bat-sat systemd[1]: Started wyoming-openwakeword.service - Wyoming openWakeWord.
Jun 07 18:16:39 bat-sat run[884]: INFO:root:Ready
Jun 07 18:17:40 bat-sat run[884]: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

```
I'll highlight the disabled part of that (the icon shows green - even though it reports disabled).  Anyone else seeing this?

**Comment by tannisroot** [comment]
> Thanks holgerb,
> 
> Increasing the swap allowed for everything to compile and move forward. That said, wakeword still seems to have an issue...
> 
> ```
> 
> ● wyoming-openwakeword.service - Wyoming openWakeWord
>      Loaded: loaded (/etc/systemd/system/wyoming-openwakeword.service; disabled; preset: enabled)
>      Active: active (running) since Fri 2024-06-07 18:16:37 EDT; 1min 11s ago
>    Main PID: 883 (python3)
>       Tasks: 9 (limit: 174)
>         CPU: 5.604s
>      CGroup: /system.slice/wyoming-openwakeword.service
>              ├─883 python3 /home/bat-sat/wyoming-openwakeword/script/run --uri tcp://127.0.0.1:10400
>              └─884 /home/bat-sat/wyoming-openwakeword/.venv/bin/python3 -m wyoming_openwakeword --uri tcp://127.0.0.1:10400
> 
> Jun 07 18:16:37 bat-sat systemd[1]: Started wyoming-openwakeword.service - Wyoming openWakeWord.
> Jun 07 18:16:39 bat-sat run[884]: INFO:root:Ready
> Jun 07 18:17:40 bat-sat run[884]: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
> ```
> 
> I'll highlight the disabled part of that (the icon shows green - even though it reports disabled). Anyone else seeing this?
> 
> More info...
> 
> ```
> bat-sat@bat-sat:~/wyoming-openwakeword/script $ ./run --uri 'tcp://127.0.0.1:10400'
> /home/bat-sat/wyoming-openwakeword/.venv/bin/python3: No module named wyoming_openwakeword
> Traceback (most recent call last):
>   File "/home/bat-sat/wyoming-openwakeword/script/./run", line 12, in <module>
>     subprocess.check_call([context.env_exe, "-m", "wyoming_openwakeword"] + sys.argv[1:])
>   File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/home/bat-sat/wyoming-openwakeword/.venv/bin/python3', '-m', 'wyoming_openwakeword', '--uri', 'tcp://127.0.0.1:10400']' returned non-zero exit status 1.
> ```
> 
> running setup completes without any errors, but it seems I'm missing a module.

You didn't specify the wakeword to load

**Comment by tannisroot** [comment]
It's also not how you test run the the service, you need to use `script/run` and not `./run`.

**Comment by tsx-5** [comment]
Hey tannisroot,

Thanks for replying, I ran that command in the script folder (sorry to not have noted that).  I also tried it with the wakeword command, without any success.  I did look at the video doing these steps and noted that "disabled" was on his output for openwakeword - so even further from knowing what the issue is.

**Comment by tannisroot** [comment]
> Hey tannisroot,
> 
> Thanks for replying, I ran that command in the script folder (sorry to not have noted that). I also tried it with the wakeword command, without any success. I did look at the video doing these steps and noted that "disabled" was on his output for openwakeword - so even further from knowing what the issue is.

It's unlikely it's related to this issue in particular, but I would bad glad to help further on Discord. Ping me on Home Assistant server, my nickname is the same as here.

**Comment by tannisroot** [comment]
For people who are running into driver installation issues, could you please try following the instructions from docs, but instead of installing the mainline wyoming-satellite repo, which corresponds with the following command
```
git clone https://github.com/rhasspy/wyoming-satellite.git
```
you install my branch with some changes that should solve the issue?
```
git clone -b adjust_compile_threads https://github.com/tannisroot/wyoming-satellite.git
```
Please let me know how it goes and whether the drivers gets successfully installed or not.

**Comment by JoshBlackstone** [comment]
> For people who are running into driver installation issues, could you please try following the instructions from docs, but instead of installing the mainline wyoming-satellite repo, which corresponds with the following command
> 
> ```
> git clone https://github.com/rhasspy/wyoming-satellite.git
> ```
> 
> you install my branch with some changes that should solve the issue?
> 
> ```
> git clone -b adjust_compile_threads https://github.com/tannisroot/wyoming-satellite.git
> ```
> 
> Please let me know how it goes and whether the drivers gets successfully installed or not.

This has worked for me. I installed it on a Raspberry Pi Zero 2 W with ReSpeaker 2Mic HAT on the non-legacy Pi OS Lite.

I got no driver errors, and everything seems to be working correctly. 

Thank you!

**Comment by tannisroot** [comment]
> > For people who are running into driver installation issues, could you please try following the instructions from docs, but instead of installing the mainline wyoming-satellite repo, which corresponds with the following command
> > ```
> > git clone https://github.com/rhasspy/wyoming-satellite.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you install my branch with some changes that should solve the issue?
> > ```
> > git clone -b adjust_compile_threads https://github.com/tannisroot/wyoming-satellite.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let me know how it goes and whether the drivers gets successfully installed or not.
> 
> This has worked for me. I installed it on a Raspberry Pi Zero 2 W with ReSpeaker 2Mic HAT on the non-legacy Pi OS Lite.
> 
> I got no driver errors, and everything seems to be working correctly.
> 
> Thank you!

Thank you so much for testing!

**Comment by edekeijzer** [comment]
Thanks a lot for this, I now swap the SD card from my Zero 2W to a Pi 3B when it's kernel update time.

**Comment by galli-miranda** [comment]
Hi @tannisroot , thank you for helping! I have tested your branch with a raspberry pi zero 2 W and the LEgacy 64 Bit lite: No success. Same error as the others in the thread on installing Open Wake Word. What I'm not sure if others tried or not, the other wakeword systems installed and worked just fine. 
Then I tested the 64 bit lite (non-legacy): Openwakeword installation worked! However, I am still struggling to get it to work. it is a USB conference speaker, not the respeaker 2mic hat, if that matters. 
Weirdly enough, when running the local wake word detection with openwakeword it just never captures anything (despite successful install), while snowboy works. 

Again, I appreciate the help so far! :)

**Comment by tannisroot** [comment]
> Hi @tannisroot , thank you for helping! I have tested your branch with a raspberry pi zero 2 W and the LEgacy 64 Bit lite: No success. Same error as the others in the thread on installing Open Wake Word. What I'm not sure if others tried or not, the other wakeword systems installed and worked just fine. Then I tested the 64 bit lite (non-legacy): Openwakeword installation worked! However, I am still struggling to get it to work. it is a USB conference speaker, not the respeaker 2mic hat, if that matters. Weirdly enough, when running the local wake word detection with openwakeword it just never captures anything (despite successful install), while snowboy works.
> 
> Again, I appreciate the help so far! :)

That's good, although my fix is aimed at fixing installation of drivers specifically for respeaker hat, if you have a USB conference speaker, you can use just the non-Legacy Raspberry Pi OS with the master branch.

**Comment by owingst** [comment]
I tried the tannisroot wyoming installer on my pi zero 2W with Raspberry Pi OS Bookworm Lite 64-bit, but still get no sound from respeaker card. I have not gotten any respeaker or waveshare wm8960 sound cards to work on Pi Zero, but waveshare cards work on Pi4/P5 just fine. Any ideas?


pi@pi0:~ $ sudo systemctl status seeed-voicecard.service
● seeed-voicecard.service - Seeed Voicecard service
     Loaded: loaded (/lib/systemd/system/seeed-voicecard.service; enabled; preset: enabled)
     Active: active (exited) since Tue 2024-07-09 11:49:48 CDT; 2min 55s ago
    Process: 1145 ExecStart=/usr/bin/seeed-voicecard (code=exited, status=0/SUCCESS)
   Main PID: 1145 (code=exited, status=0/SUCCESS)
        CPU: 505ms

Jul 09 11:49:48 pi0 seeed-voicecard[1184]: alsa-lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
Jul 09 11:49:48 pi0 seeed-voicecard[1184]: No state is present for card vc4hdmi
Jul 09 11:49:48 pi0 seeed-voicecard[1184]: alsa-lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2
Jul 09 11:49:48 pi0 seeed-voicecard[1184]: Found hardware: "vc4-hdmi" "" "" "" ""
Jul 09 11:49:48 pi0 seeed-voicecard[1184]: Hardware is initialized using a generic method
Jul 09 11:49:48 pi0 seeed-voicecard[1184]: No state is present for card vc4hdmi
Jul 09 11:49:48 pi0 seeed-voicecard[1184]: alsa-lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -2
Jul 09 11:49:48 pi0 seeed-voicecard[1185]: + aplay -l
Jul 09 11:49:48 pi0 seeed-voicecard[1186]: + grep -q 'bcm2835 ALSA'
Jul 09 11:49:48 pi0 systemd[1]: Finished seeed-voicecard.service - Seeed Voicecard service.

**Comment by owingst** [comment]
I was able to get sound from soundcard when I hooked up a speaker to jst connector. I have been using a speaker attached to audio jack and never got any sound. Thanks!

**Comment by tannisroot** [comment]
> I tried the tannisroot wyoming installer on my pi zero 2W with Raspberry Pi OS Bookworm Lite 64-bit, but still get no sound from respeaker card. I have not gotten any respeaker or waveshare wm8960 sound cards to work on Pi Zero, but waveshare cards work on Pi4/P5 just fine. Any ideas?
> 
> pi@pi0:~ $ sudo systemctl status seeed-voicecard.service ● seeed-voicecard.service - Seeed Voicecard service Loaded: loaded (/lib/systemd/system/seeed-voicecard.service; enabled; preset: enabled) Active: active (exited) since Tue 2024-07-09 11:49:48 CDT; 2min 55s ago Process: 1145 ExecStart=/usr/bin/seeed-voicecard (code=exited, status=0/SUCCESS) Main PID: 1145 (code=exited, status=0/SUCCESS) CPU: 505ms
> 
> Jul 09 11:49:48 pi0 seeed-voicecard[1184]: alsa-lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2 Jul 09 11:49:48 pi0 seeed-voicecard[1184]: No state is present for card vc4hdmi Jul 09 11:49:48 pi0 seeed-voicecard[1184]: alsa-lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2 Jul 09 11:49:48 pi0 seeed-voicecard[1184]: Found hardware: "vc4-hdmi" "" "" "" "" Jul 09 11:49:48 pi0 seeed-voicecard[1184]: Hardware is initialized using a generic method Jul 09 11:49:48 pi0 seeed-voicecard[1184]: No state is present for card vc4hdmi Jul 09 11:49:48 pi0 seeed-voicecard[1184]: alsa-lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:1 use case configuration -2 Jul 09 11:49:48 pi0 seeed-voicecard[1185]: + aplay -l Jul 09 11:49:48 pi0 seeed-voicecard[1186]: + grep -q 'bcm2835 ALSA' Jul 09 11:49:48 pi0 systemd[1]: Finished seeed-voicecard.service - Seeed Voicecard service.

FYI my changed were merged and it's ok to use master now
