### ISSUE TITLE
RPI 4 + respeaker 2mic numpy.core.multiarray error

### ISSUE THREAD

**Issue by fluvio89** [rhasspy/wyoming-satellite#179]
Hello, 

I'm stumped...

wyoming-wakeword.service - openWakeWord
     Loaded: loaded (/etc/systemd/system/wyoming-wakeword.service; enabled; preset: enabled)
     Active: active (running) since Mon 2024-06-17 22:00:44 CEST; 41min ago
   Main PID: 2218 (python3)
      Tasks: 5 (limit: 3917)
        CPU: 40.310s
     CGroup: /system.slice/wyoming-wakeword.service
             ├─2218 python3 /home/satellite/wyoming-satellite/local/wyoming-openwakeword/script/run --uri tcp://127.0.0.1:10400 --thresho>
             └─2220 /home/satellite/wyoming-satellite/local/wyoming-openwakeword/.venv/bin/python3 -m wyoming_openwakeword --uri tcp://12>

Jun 17 22:42:01 altoparlante run[2220]: ImportError: numpy.core.multiarray failed to import
Jun 17 22:42:01 altoparlante run[2220]: The above exception was the direct cause of the following exception:
Jun 17 22:42:01 altoparlante run[2220]: Traceback (most recent call last):
Jun 17 22:42:01 altoparlante run[2220]:   File "/home/satellite/wyoming-satellite/local/wyoming-openwakeword/wyoming_openwakeword/openwak>
Jun 17 22:42:01 altoparlante run[2220]:     ww_model = tflite.Interpreter(model_path=str(ww_model_path), num_threads=1)
Jun 17 22:42:01 altoparlante run[2220]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 17 22:42:01 altoparlante run[2220]:   File "/home/satellite/wyoming-satellite/local/wyoming-openwakeword/.venv/lib/python3.11/site-pa>
Jun 17 22:42:01 altoparlante run[2220]:     self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
Jun 17 22:42:01 altoparlante run[2220]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 17 22:42:01 altoparlante run[2220]: SystemError: <built-in method CreateWrapperFromFile of PyCapsule object at 0x7f89936bb0> returned>

i'm a total noob but i cannot get it to work at all... :(

**Comment by spencermccarthy** [comment]
so funny that there are 2 people in the world doing the same thing and having the same issue. :D 

Looking like there's been a NumPy update.

My full error log is: -

Jun 18 10:24:05 office-satellite run[603]: A module that was compiled using NumPy 1.x cannot be run in
Jun 18 10:24:05 office-satellite run[603]: NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
Jun 18 10:24:05 office-satellite run[603]: versions of NumPy, modules must be compiled with NumPy 2.0.
Jun 18 10:24:05 office-satellite run[603]: Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
Jun 18 10:24:05 office-satellite run[603]: If you are a user of the module, the easiest solution will be to
Jun 18 10:24:05 office-satellite run[603]: downgrade to 'numpy<2' or try to upgrade the affected module.
Jun 18 10:24:05 office-satellite run[603]: We expect that some modules will need time to support NumPy 2.
Jun 18 10:24:05 office-satellite run[603]: Traceback (most recent call last):  File "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
Jun 18 10:24:05 office-satellite run[603]:     self._bootstrap_inner()
Jun 18 10:24:05 office-satellite run[603]:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Jun 18 10:24:05 office-satellite run[603]:     self.run()
Jun 18 10:24:05 office-satellite run[603]:   File "/usr/lib/python3.11/threading.py", line 975, in run
Jun 18 10:24:05 office-satellite run[603]:     self._target(*self._args, **self._kwargs)
Jun 18 10:24:05 office-satellite run[603]:   File "/home/admin/wyoming-openwakeword/wyoming_openwakeword/openwakeword.py", line 248, in ww_proc
Jun 18 10:24:05 office-satellite run[603]:     ww_model = tflite.Interpreter(model_path=str(ww_model_path), num_threads=1)
Jun 18 10:24:05 office-satellite run[603]:   File "/home/admin/wyoming-openwakeword/.venv/lib/python3.11/site-packages/tflite_runtime/interpreter.py", line 473, in __init__
Jun 18 10:24:05 office-satellite run[603]:     self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
Jun 18 10:24:05 office-satellite run[603]: AttributeError: _ARRAY_API not found
Jun 18 10:24:05 office-satellite run[603]: ERROR:root:Unexpected error in wake word thread (ok_nabu_v0.1)
Jun 18 10:24:05 office-satellite run[603]: ImportError: numpy.core.multiarray failed to import
Jun 18 10:24:05 office-satellite run[603]: The above exception was the direct cause of the following exception:
Jun 18 10:24:05 office-satellite run[603]: Traceback (most recent call last):
Jun 18 10:24:05 office-satellite run[603]:   File "/home/admin/wyoming-openwakeword/wyoming_openwakeword/openwakeword.py", line 248, in ww_proc
Jun 18 10:24:05 office-satellite run[603]:     ww_model = tflite.Interpreter(model_path=str(ww_model_path), num_threads=1)
Jun 18 10:24:05 office-satellite run[603]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 18 10:24:05 office-satellite run[603]:   File "/home/admin/wyoming-openwakeword/.venv/lib/python3.11/site-packages/tflite_runtime/interpreter.py", line 473, in __init__
Jun 18 10:24:05 office-satellite run[603]:     self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
Jun 18 10:24:05 office-satellite run[603]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 18 10:24:05 office-satellite run[603]: SystemError: <built-in method CreateWrapperFromFile of PyCapsule object at 0x7f905c0ff0> returned a result with an exception set

**Comment by fluvio89** [comment]
> so funny that there are 2 people in the world doing the same thing and having the same issue. :D
> 
> Looking like there's been a NumPy update.

yeah that’s insane :) 

I have absolutely no idea what to do to resolve the issue 😂

**Comment by st0ne** [comment]
3 people ;-)

**Comment by spencermccarthy** [comment]
@st0ne Do you have to rerun the setup script after doing that, or fresh build?

**Comment by st0ne** [comment]
yes i have just done the setup script again. It looks like pip is automatically uninstalling numpy2 and installing the old version.

now i have a different error. wyoming-satellite.service cannot connect to 127.0.0.1 port 10400, but this is maybe another problem.

**Comment by spencermccarthy** [comment]
I've added the version control to the requirement.txt file and rerun the script/setup. I saw it pull down the numpy version and now it looks like things are starting ok.

**Comment by st0ne** [comment]
i dont know why the connection error appears, but it is working now :-)

**Comment by fluvio89** [comment]
Gonna try this as soon as I get home, thanks

**Comment by fluvio89** [comment]
ok, seems to work! Now, on to installing different wake words :)
