### ISSUE TITLE
Satellite not starting

### ISSUE THREAD

**Issue by tebbbb** [rhasspy/wyoming-satellite#192]
I used the installer and the service always fails. I tried to execute the command manually:

xxx@wyoming1:~ $ /home/xxx/wyoming-satellite/script/run --name WyomingOffice --uri tcp://0.0.0.0:10700 --mic-command 'arecord -D default -q -r 16000 -c 1 -f S16_LE -t raw' --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -q -r 22050 -c 1 -f S16_LE -t raw' --awake-wav /home/xxx/wyoming-satellite/sounds/awake.wav --done-wav /home/xxx/wyoming-satellite/sounds/done.wav --mic-noise-suppression 2 --mic-auto-gain 5 --wake-uri tcp://127.0.0.1:10400 --wake-word-name ok_nabu --event-uri tcp://127.0.0.1:10500
/home/xxx/wyoming-satellite/.venv/bin/python3: No module named wyoming_satellite
Traceback (most recent call last):
  File "/home/xxx/wyoming-satellite/script/run", line 12, in <module>
    subprocess.check_call([context.env_exe, "-m", "wyoming_satellite"] + sys.argv[1:])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/xxx/wyoming-satellite/.venv/bin/python3', '-m', 'wyoming_satellite', '--name', 'WyomingOffice', '--uri', 'tcp://0.0.0.0:10700', '--mic-command', 'arecord -D default -q -r 16000 -c 1 -f S16_LE -t raw', '--snd-command', 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -q -r 22050 -c 1 -f S16_LE -t raw', '--awake-wav', '/home/xxx/wyoming-satellite/sounds/awake.wav', '--done-wav', '/home/xxx/wyoming-satellite/sounds/done.wav', '--mic-noise-suppression', '2', '--mic-auto-gain', '5', '--wake-uri', 'tcp://127.0.0.1:10400', '--wake-word-name', 'ok_nabu', '--event-uri', 'tcp://127.0.0.1:10500']' returned non-zero exit status 1.

**Comment by formatBCE** [comment]
Same stuff here, looks like noise-suppression or auto-gain causing this.

**Comment by formatBCE** [comment]
Actually, i re-typed all problematic places with my hands instead of copy-pasting, and it works now.
