### ISSUE TITLE
Installer with timer option ?

### ISSUE THREAD

**Issue by faduchesne** [rhasspy/wyoming-satellite#198]
Is it possible to have a version of the installer with the option for timers soon? I have tried several times to modify the service file, but it doesn't work. For regular users, it remains very complicated... Thank you very much.

**Comment by tannisroot** [comment]
The project already added it quite a long time ago. You need to update the local repository with `git pull`

**Comment by tannisroot** [comment]
Oh and you need to add these

**Comment by tannisroot** [comment]
```
    --timer-finished-wav 'sounds/timer_finished.wav' \
    --timer-finished-wav-repeat 3 3 \

```

**Comment by tannisroot** [comment]
You may need to change `3 3` to your preference, one is delay and the other is how many times the sound is repeated

**Comment by synesthesiam** [comment]
Thank you @tannisroot

**Comment by mkcologne** [comment]
> ```
>     --timer-finished-wav 'sounds/timer_finished.wav' \
>     --timer-finished-wav-repeat 3 3 \
> ```

Hi!
I've added those lines and get an error while the service ist starting:

> Jul 18 11:21:44 sat1 run[907]: __main__.py: error: ambiguous option: --timer could match --timer-started-command, --timer-updated-command, -->
Jul 18 11:21:44 sat1 run[903]: Traceback (most recent call last):
Jul 18 11:21:44 sat1 run[903]:   File "/home/pi/wyoming-satellite/script/run", line 12, in <module>
Jul 18 11:21:44 sat1 run[903]:     subprocess.check_call([context.env_exe, "-m", "wyoming_satellite"] + sys.argv[1:])
Jul 18 11:21:44 sat1 run[903]:   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
Jul 18 11:21:44 sat1 run[903]:     raise CalledProcessError(retcode, cmd)
Jul 18 11:21:44 sat1 run[903]: subprocess.CalledProcessError: Command '['/home/pi/wyoming-satellite/.venv/bin/python3', '-m', 'wyoming_satell>
Jul 18 11:21:44 sat1 systemd[1]: wyoming-satellite.service: Main process exited, code=exited, status=1/FAILURE

**Comment by tannisroot** [comment]
Can you copy and paste your entire config here, as well as share path to your wyoming-satellite folder

**Comment by mkcologne** [comment]
For sure:

```
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=2mic_leds.service

[Service]
Type=simple
ExecStart=/home/pi/wyoming-satellite/script/run \
--name 'kHome Sat 1' \
--uri 'tcp://0.0.0.0:10700' \
--mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
--snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 44100 -c 1 -f S16_LE -t raw' \
--snd-command-rate 44100 \
--mic-auto-gain 5 \
--mic-noise-suppression 2 \
--wake-uri 'tcp://127.0.0.1:10400' \
--wake-word-name 'hey_jarvis' \
--event-uri 'tcp://127.0.0.1:10500' \
--awake-wav sounds/awake.wav \
##--timer-finished-wav 'sounds/timer_finished.wav' \
##--timer finished-wav-repeat 5 1 \ 

WorkingDirectory=/home/pi/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target


```

Timers are commented out for reasons.

M.

**Comment by tannisroot** [comment]
You need to remove the last \ from the timer option.

**Comment by mkcologne** [comment]
Thanks!

For my understanding:
Why is the trailing ' \ ' by --awake-wav not a problem but by --timer … it is?

**Comment by tannisroot** [comment]
> Thanks!
> 
> For my understanding: Why is the trailing ' \ ' by --awake-wav not a problem but by --timer … it is?

In bash, \ + newline character (invisible but dictates when a new line is created) is interpreted as line continuation. Your `--timer finished-wav-repeat 5 1` option is last so it needs to be the end of the line without anything continuing after that.
In my config, those 2 options are in the middle of the list of the configs so it works.

**Comment by zwolfinger** [comment]
I'm running into the same problem I think.  

1. I'm running the latest version of HA (2024.8.0)
2. I'm running the latest version of wyoming-satellite on my Pi zero 2w (wyoming-satellite/wyoming-satellite/VERSION shows 1.3.0)
3. I'm running the latest version of wyoming (1.5.4)

Here is my service file: 
`[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=2mic_leds.service

[Service]
Type=simple
WorkingDirectory=/home/pi/wyoming-satellite
ExecStart=/home/pi/wyoming-satellite/script/run \
        --name 'wyoming-den' \
        --uri 'tcp://0.0.0.0:10700' \
        --mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
        --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 22050 -c 1 -f S16_LE -t raw' \
        --mic-auto-gain 5 \
        --mic-noise-suppression 2 \
        --wake-uri 'tcp://127.0.0.1:10400' \
        --wake-word-name 'hey_jarvis' \
        --event-uri 'tcp://127.0.0.1:10500' \
        --timer-finished-wav '/home/pi/wyoming-satellite/sounds/timer_finished.wav' \
        --timer-finished-wav-repeat 3 3

Restart=always
RestartSec=1

[Install]
WantedBy=default.target
`

I get audio confirmation that the timer has started, but I never get anything when the timer finishes.

I've also tried replacing the --timer-finished-wav and --timer-finished-wav-repeat with '--timer-finished-command /home/pi/wyoming-satellite/end_timer.sh' containing 
`#!/bin/bash
aplay -D plughw:CARD=seeed2micvoicec,DEV=0 /home/zwolfinger/wyoming-satellite/sounds/end_timer.wav
`
and set to executable (chmod +x end_timer.wav).  The script works fine when I call it from the command line.

It feels like wyoming-satellite isn't getting told that the timer has finished so it never plays the file or runs the command.   Is there something else on the HA side I need to do?  Any other ideas?

**Comment by tannisroot** [comment]
> I'm running into the same problem I think.
> 
>     1. I'm running the latest version of HA (2024.8.0)
> 
>     2. I'm running the latest version of wyoming-satellite on my Pi zero 2w (wyoming-satellite/wyoming-satellite/VERSION shows 1.3.0)
> 
>     3. I'm running the latest version of wyoming (1.5.4)
> 
> 
> Here is my service file: `[Unit] Description=Wyoming Satellite Wants=network-online.target After=network-online.target Requires=wyoming-openwakeword.service Requires=2mic_leds.service
> 
> [Service] Type=simple WorkingDirectory=/home/pi/wyoming-satellite ExecStart=/home/pi/wyoming-satellite/script/run --name 'wyoming-den' --uri 'tcp://0.0.0.0:10700' --mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 22050 -c 1 -f S16_LE -t raw' --mic-auto-gain 5 --mic-noise-suppression 2 --wake-uri 'tcp://127.0.0.1:10400' --wake-word-name 'hey_jarvis' --event-uri 'tcp://127.0.0.1:10500' --timer-finished-wav '/home/pi/wyoming-satellite/sounds/timer_finished.wav' --timer-finished-wav-repeat 3 3
> 
> Restart=always RestartSec=1
> 
> [Install] WantedBy=default.target `
> 
> I get audio confirmation that the timer has started, but I never get anything when the timer finishes.
> 
> I've also tried replacing the --timer-finished-wav and --timer-finished-wav-repeat with '--timer-finished-command /home/pi/wyoming-satellite/end_timer.sh' containing `#!/bin/bash aplay -D plughw:CARD=seeed2micvoicec,DEV=0 /home/zwolfinger/wyoming-satellite/sounds/end_timer.wav ` and set to executable (chmod +x end_timer.wav). The script works fine when I call it from the command line.
> 
> It feels like wyoming-satellite isn't getting told that the timer has finished so it never plays the file or runs the command. Is there something else on the HA side I need to do? Any other ideas?

In the config, the path contains `/home/pi`, pi being the user, but from the snippet you've shared, your user is `zwolfinger`.
The guide assumes you leave the user name at default.

**Comment by zwolfinger** [comment]
Actually I tried to anonymize my code for the comment and missed one. It IS all /home/zwolfinger in the real files. 

Still no joy.

**Comment by tannisroot** [comment]
> Actually I tried to anonymize my code for the comment and missed one. It IS all /home/zwolfinger in the real files.
> 
> Still no joy.

Please provide `journalctl -u wyoming-satellite.service`

**Comment by ryuzaki09** [comment]
I am also having this same issue.
when I ask to set timer, the logs just stops here:
```
Mar 05 10:19:48 satellite-dining run[742]: Wed 5 Mar 10:19:48 GMT 2025 [awake.sh] ...Starting awake.sh script
Mar 05 10:19:48 satellite-dining run[742]: Wed 5 Mar 10:19:48 GMT 2025 [awake.sh] ...Starting silence
```
there is no response either to say something like 'timer has been started'

this is my config
```
[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=2mic_leds.service
Requires=pulseaudio.service

[Service]
Type=simple
ExecStart=/home/pi/wyoming-satellite/script/run --name 'Satellite Dining Room' \
	--uri 'tcp://0.0.0.0:10700' \
	--mic-command 'parecord --property=media.role=phone --rate=16000 --channels=1 --format=s16le --raw --latency-msec 10' \
	--snd-command 'paplay --property=media.role=announce --rate=44100 --channels=1 --format=s16le --raw --latency-msec 10' \
	--snd-command-rate 44100 \
	--mic-volume-multiplier 0.5 \
	--mic-auto-gain 5 \
	--mic-noise-suppression 3 \
	--event-uri 'tcp://127.0.0.1:10500' \
	--wake-uri 'tcp://127.0.0.1:10400' \
	--wake-word-name 'bay_max' \
	--detection-command '/home/pi/wyoming-enhancements/snapcast/scripts/awake.sh' \
	--tts-stop-command '/home/pi/wyoming-enhancements/snapcast/scripts/done.sh' \
	--error-command '/home/pi/wyoming-enhancements/snapcast/scripts/done.sh' \
	--timer-finished-wav sounds/timer_finished.wav \
	--timer-finished-wav-repeat 3 3 \
        --awake-wav sounds/awake.wav \
	--done-wav sounds/done.wav

WorkingDirectory=/home/pi/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target
```

any ideas?

**Comment by tannisroot** [comment]
> I am also having this same issue. when I ask to set timer there is no response to say something like 'timer has been started'
> 
> this is my config
> 
> ```
> [Unit]
> Description=Wyoming Satellite
> Wants=network-online.target
> After=network-online.target
> Requires=wyoming-openwakeword.service
> Requires=2mic_leds.service
> Requires=pulseaudio.service
> 
> [Service]
> Type=simple
> ExecStart=/home/pi/wyoming-satellite/script/run --name 'Satellite Dining Room' \
> 	--uri 'tcp://0.0.0.0:10700' \
> 	--mic-command 'parecord --property=media.role=phone --rate=16000 --channels=1 --format=s16le --raw --latency-msec 10' \
> 	--snd-command 'paplay --property=media.role=announce --rate=44100 --channels=1 --format=s16le --raw --latency-msec 10' \
> 	--snd-command-rate 44100 \
> 	--mic-volume-multiplier 0.5 \
> 	--mic-auto-gain 5 \
> 	--mic-noise-suppression 3 \
> 	--event-uri 'tcp://127.0.0.1:10500' \
> 	--wake-uri 'tcp://127.0.0.1:10400' \
> 	--wake-word-name 'bay_max' \
> 	--detection-command '/home/pi/wyoming-enhancements/snapcast/scripts/awake.sh' \
> 	--tts-stop-command '/home/pi/wyoming-enhancements/snapcast/scripts/done.sh' \
> 	--error-command '/home/pi/wyoming-enhancements/snapcast/scripts/done.sh' \
> 	--timer-finished-wav sounds/timer_finished.wav \
> 	--timer-finished-wav-repeat 3 3 \
>         --awake-wav sounds/awake.wav \
> 	--done-wav sounds/done.wav
> 
> WorkingDirectory=/home/pi/wyoming-satellite
> Restart=always
> RestartSec=1
> 
> [Install]
> WantedBy=default.target
> ```
> 
> Another note is, this only happens if I use the ExtendedOpenAI pipeline, I get this response:
> 
> ```
> Something went wrong: Unable to find entity ['timer.timer']
> ```
> 
> but when I use the default "Home Assistant" assist pipeline, it works fine.
> 
> please, any help would be appreciated.

If normal assist pipeline works fine and the issue is only with ExtendedOpenAI custom integration, you need to report this to ExtendedOpenAI.

**Comment by tiagocunico** [comment]
Hey, I know this is kinda of an old tread, but I'm having the exactly same problem. The system start and ends the timer, but never play any sound when it finished the timer.

I used the installer, and it worked great, but didn't had the lines for when the sound finished, so i add this 2 lines.

> --timer-finished-wav 'sounds/timer_finished.wav' \
    --timer-finished-wav-repeat 3 3 \

in the end my source file is like this

>[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-wakeword.service

>[Service]
Type=simple
User=tiago
Environment=XDG_RUNTIME_DIR=/run/user/1000
ExecStart=/home/tiago/wyoming-satellite/script/run --name 'Satelite quarto' --uri tcp://0.0.0.0:10700 --mic-command 'arecord -D plughw:CARD=Device,DEV=0 -q -r 16000 -c 1 -f S16_LE -t raw' --snd-command 'aplay -D plughw:CARD=Headphones,DEV=0 -q -r 22050 -c 1 -f S16_LE -t raw' --awake-wav /home/tiago/wyoming-satellite/sounds/awake.wav --done-wav /home/tiago/wyoming-satellite/sounds/done.wav --mic-noise-suppression 1 --mic-auto-gain 30 --wake-uri tcp://127.0.0.1:10400 --wake-word-name alexa --timer-finished-wav /home/tiago/wyoming-satellite/sounds/timer_finished.wav --timer-finished-wav-repeat 3 3 --debug --debug-recording-dir /home/tiago/wyoming-satellite/local/debug-recording
WorkingDirectory=/home/tiago/wyoming-satellite
Restart=always
RestartSec=1

>[Install]
WantedBy=default.target




This is my logs using the `journalctl -u wyoming-satellite.service` comand.
> Aug 24 15:16:54 ha-satelite-quarto run[684]: DEBUG:root:Detection(name='alexa_v0.1', timestamp=574907706077, speaker=None)
Aug 24 15:16:54 ha-satelite-quarto run[684]: DEBUG:root:Streaming audio
Aug 24 15:16:54 ha-satelite-quarto run[684]: DEBUG:root:Event(type='run-pipeline', data={'start_stage': 'asr', 'end_stage': 'tts', 'restart_on_end': False, 'snd_format': {'rate': 22050, 'width': 2, 'channels': 1}}, payload=None)
Aug 24 15:16:54 ha-satelite-quarto run[684]: DEBUG:root:Muting microphone for 0.8995918367346939 second(s)
Aug 24 15:16:54 ha-satelite-quarto run[684]: DEBUG:root:Connected to snd service
Aug 24 15:16:54 ha-satelite-quarto run[684]: DEBUG:root:Unmuted microphone
Aug 24 15:16:59 ha-satelite-quarto run[684]: DEBUG:root:Stopped recording to /home/tiago/wyoming-satellite/local/debug-recording/527096381683-stt.wav
Aug 24 15:16:59 ha-satelite-quarto run[684]: DEBUG:root:Event(type='transcript', data={'text': 'Timers de um minuto.'}, payload=None)
Aug 24 15:16:59 ha-satelite-quarto run[684]: INFO:root:Waiting for wake word
Aug 24 15:16:59 ha-satelite-quarto run[684]: DEBUG:root:Started recording to /home/tiago/wyoming-satellite/local/debug-recording/580542416059-wake.wav
Aug 24 15:16:59 ha-satelite-quarto run[684]: DEBUG:root:Event(type='timer-started', data={'id': '01K3EMRH1A31A577JAZ03DH3MV', 'total_seconds': 60, 'start_minutes': 1}, payload=None)
Aug 24 15:16:59 ha-satelite-quarto run[684]: DEBUG:root:Event(type='synthesize', data={'text': 'Temporizador iniciado', 'voice': {'name': 'pt_BR-faber-medium'}}, payload=None)
Aug 24 15:16:59 ha-satelite-quarto run[684]: DEBUG:root:Connected to snd service
Aug 24 15:17:00 ha-satelite-quarto run[684]: DEBUG:root:Connected to snd service
Aug 24 15:17:59 ha-satelite-quarto run[684]: DEBUG:root:Event(type='timer-finished', data={'id': '01K3EMRH1A31A577JAZ03DH3MV'}, payload=None)


What can i do?
Please, any help would be appreciated.
