### ISSUE TITLE
Awake wav does not play/Crackling audio from piper

### ISSUE THREAD

**Issue by vhsdream** [rhasspy/wyoming-satellite#2]
I have wyoming-openwakeword and wyoming-satellite running on a raspberry pi 3B.

I've managed to get local wakeword detection working, however the awake wav does not play when the word is detected. The done sound plays after I have finished speaking, as intended.

The other issue I have noted is when the response comes back (for example "turned on light"), the audio is cracking. It did not sound like that when I used the homeassistant-satellite. I'll share the commands for wyoming-satellite and openwakeword below.

### openwakeword

```shell
--uri 'tcp://0.0.0.0:10400' --threshold 0.3 --trigger-level 2 --preload-model ok_nabu --preload-model alexa --debug
``` 

### wyoming-satellite

```shell
--uri 'tcp://0.0.0.0:10700' --name 'test-sat' --mic-command 'arecord -D plughw:CARD=S330,DEV=0 -r 16000 -f S16_LE' --snd-command 'aplay -D plughw:CARD=S330,DEV=0 -r 22050 -f S16_LE' --snd-volume-multiplier 0.25 --wake-uri 'tcp://127.0.0.1:10400' --noise-suppression 4 --auto-gain 31 --awake-wav sounds/awake.wav --done-wav sounds/done.wav --no-zeroconf --debug
``` 

Here is the debug output from the satellite

DEBUG:root:Client connected: 92513916168445
DEBUG:root:Running arecord -D plughw:CARD=S330,DEV=0 -r 16000 -f S16_LE
DEBUG:root:Connecting to tcp://127.0.0.1:10400
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
INFO:root:Detecting wake word
DEBUG:root:Event(type='detect', data={'names': None}, payload=None)
DEBUG:root:Wake word detected: Event(type='detection', data={'name': 'ok_nabu_v0.1', 'timestamp': 92520337643771}, payload=None)
INFO:root:Streaming audio
DEBUG:root:Event(type='transcribe', data={'language': 'en'}, payload=None)
DEBUG:root:Event(type='voice-started', data={'timestamp': 695}, payload=None)
DEBUG:root:Event(type='voice-stopped', data={'timestamp': 1265}, payload=None)
DEBUG:root:Running aplay -D plughw:CARD=S330,DEV=0 -r 22050 -f S16_LE
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
INFO:root:Detecting wake word
DEBUG:root:Event(type='transcript', data={'text': ' Turn on the Christmas lights.'}, payload=None)
DEBUG:root:Event(type='synthesize', data={'text': 'Turned on light', 'voice': {'name': 'en_US-libritts_r-medium'}}, payload=None)
DEBUG:root:Running aplay -D plughw:CARD=S330,DEV=0 -r 22050 -f S16_LE
DEBUG:root:Event(type='audio-start', data={'rate': 16000, 'width': 2, 'channels': 1, 'timestamp': 0}, payload=None)
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
DEBUG:root:Event(type='audio-stop', data={'timestamp': 0.9082500000000003}, payload=None)
DEBUG:root:Event(type='transcribe', data={'language': 'en'}, payload=None)

If I modify the '--snd-command' to `--snd-command 'aplay -D plughw:CARD=S330 -r 22050 -c 1 -f S16_LE -t wav` there is a different error, and the awake wav still does not play, and neither does the response from piper:

DEBUG:root:Connecting to tcp://127.0.0.1:10400
INFO:root:Detecting wake word
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
DEBUG:root:Event(type='detect', data={'names': None}, payload=None)
DEBUG:root:Wake word detected: Event(type='detection', data={'name': 'alexa_v0.1', 'timestamp': 92915555640606}, payload=None)
INFO:root:Streaming audio
DEBUG:root:Event(type='transcribe', data={'language': 'en'}, payload=None)
DEBUG:root:Event(type='voice-started', data={'timestamp': 765}, payload=None)
DEBUG:root:Event(type='voice-stopped', data={'timestamp': 1325}, payload=None)
DEBUG:root:Running aplay -D plughw:CARD=S330,DEV=0 -r 22050 -c 1 -f S16_LE -t wav
ERROR:root:Unexpected error while playing WAV: sounds/done.wav
Traceback (most recent call last):
  File "/home/chris/wyoming-satellite/wyoming_satellite/__main__.py", line 752, in _play_wav
    await self.snd_client.write_event(event)
  File "/home/chris/wyoming-satellite/.venv/lib/python3.9/site-packages/wyoming/snd.py", line 97, in write_event
    await self._proc.stdin.drain()
  File "/usr/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
INFO:root:Detecting wake word
DEBUG:root:Event(type='transcript', data={'text': ' Turn on the Christmas lights.'}, payload=None)
DEBUG:root:Event(type='synthesize', data={'text': 'Turned on light', 'voice': {'name': 'en_US-hfc_male-medium'}}, payload=None)
DEBUG:root:Running aplay -D plughw:CARD=S330,DEV=0 -r 22050 -c 1 -f S16_LE -t wav
DEBUG:root:Event(type='audio-start', data={'rate': 16000, 'width': 2, 'channels': 1, 'timestamp': 0}, payload=None)
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-5' coro=<AsyncEventHandler.run() done, defined at /home/chris/wyoming-satellite/.venv/lib/python3.9/site-packages/wyoming/server.py:28> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/home/chris/wyoming-satellite/.venv/lib/python3.9/site-packages/wyoming/server.py", line 35, in run
    if not (await self.handle_event(event)):
  File "/home/chris/wyoming-satellite/wyoming_satellite/__main__.py", line 378, in handle_event
    await self.snd_client.write_event(event)
  File "/home/chris/wyoming-satellite/.venv/lib/python3.9/site-packages/wyoming/snd.py", line 97, in write_event
    await self._proc.stdin.drain()
  File "/usr/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

**Comment by synesthesiam** [comment]
The awake wav part may be fixed in the latest code, but the crackling is due to resampling. Since Python is "brilliantly" removing `audioop`, I tried to write my own in Python based on the C code :grimacing: 

I plan to add some fallback code to use `audioop` while it's still available and fall back to `sox` or `ffmpeg` before using my stuff.

**Comment by that1guy** [comment]
FYI - I resolved the auto popping/crackling issue by slighly modifying the `--snd-command` flag in my `wyoming-satellite.service` to 16000.  See below.

`--snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' --snd-command-rate 16000`
