### ISSUE TITLE
Wake word model not found: ok_jarvis

### ISSUE THREAD

**Issue by chezpaul** [rhasspy/wyoming-satellite#242]
I just installed all three services: wyoming-satellite, wyoming-openwakeword and 2mic_leds
They seem to all be up and running but I get an error with the wakeword:

`● wyoming-satellite.service - Wyoming Satellite
     Loaded: loaded (/etc/systemd/system/wyoming-satellite.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-11-29 14:09:00 PST; 1s ago
   Main PID: 4478 (python3)
      Tasks: 2 (limit: 173)
        CPU: 1.123s
     CGroup: /system.slice/wyoming-satellite.service
             ├─4478 python3 /home/lvsatellite/wyoming-satellite/script/run --name lvsatellite --uri tcp://0.0.0.0:10700 --mic-command "arecord -D p>
             └─4479 /home/lvsatellite/wyoming-satellite/.venv/bin/python3 -m wyoming_satellite --name lvsatellite --uri tcp://0.0.0.0:10700 --mic-c>

Nov 29 14:09:01 lvsatellite run[4479]:                    [--timer-finished-command TIMER_FINISHED_COMMAND]
Nov 29 14:09:01 lvsatellite run[4479]:                    [--awake-wav AWAKE_WAV] [--done-wav DONE_WAV]
Nov 29 14:09:01 lvsatellite run[4479]:                    [--timer-finished-wav TIMER_FINISHED_WAV]
Nov 29 14:09:01 lvsatellite run[4479]:                    [--timer-finished-wav-repeat repeat delay] --uri URI
Nov 29 14:09:01 lvsatellite run[4479]:                    [--name NAME] [--area AREA] [--no-zeroconf]
Nov 29 14:09:01 lvsatellite run[4479]:                    [--zeroconf-name ZEROCONF_NAME]
Nov 29 14:09:01 lvsatellite run[4479]:                    [--zeroconf-host ZEROCONF_HOST]
Nov 29 14:09:01 lvsatellite run[4479]:                    [--debug-recording-dir DEBUG_RECORDING_DIR] [--debug]
Nov 29 14:09:01 lvsatellite run[4479]:                    [--log-format LOG_FORMAT] [--version]
Nov 29 14:09:01 lvsatellite run[4479]: __main__.py: error: ambiguous option: --snd=command-rate could match --snd-uri, --snd-command, --snd-command>

● wyoming-openwakeword.service - Wyoming openWakeWord
     Loaded: loaded (/etc/systemd/system/wyoming-openwakeword.service; disabled; preset: enabled)
     Active: active (running) since Fri 2024-11-29 11:51:47 PST; 2h 17min ago
   Main PID: 3061 (python3)
      Tasks: 57 (limit: 173)
        CPU: 41min 22.711s
     CGroup: /system.slice/wyoming-openwakeword.service
             ├─3061 python3 /home/lvsatellite/wyoming-openwakeword/script/run --uri tcp://127.0.0.1:10400
             └─3064 /home/lvsatellite/wyoming-openwakeword/.venv/bin/python3 -m wyoming_openwakeword --uri tcp://127.0.0.1:10400

Nov 29 11:51:49 lvsatellite run[3064]: future: <Task finished name='wyoming event handler' coro=<AsyncEventHandler.run() done, defined at /home/lvs>
Nov 29 11:51:49 lvsatellite run[3064]: Traceback (most recent call last):
Nov 29 11:51:49 lvsatellite run[3064]:   File "/home/lvsatellite/wyoming-openwakeword/.venv/lib/python3.11/site-packages/wyoming/server.py", line 4>
Nov 29 11:51:49 lvsatellite run[3064]:     if not (await self.handle_event(event)):
Nov 29 11:51:49 lvsatellite run[3064]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 29 11:51:49 lvsatellite run[3064]:   File "/home/lvsatellite/wyoming-openwakeword/wyoming_openwakeword/handler.py", line 76, in handle_event
Nov 29 11:51:49 lvsatellite run[3064]:     ensure_loaded(
Nov 29 11:51:49 lvsatellite run[3064]:   File "/home/lvsatellite/wyoming-openwakeword/wyoming_openwakeword/handler.py", line 244, in ensure_loaded
Nov 29 11:51:49 lvsatellite run[3064]:     raise ValueError(f"Wake word model not found: {model_name}")
Nov 29 11:51:49 lvsatellite run[3064]: ValueError: Wake word model not found: ok_jarvis

● 2mic_leds.service - 2Mic LEDs
     Loaded: loaded (/etc/systemd/system/2mic_leds.service; disabled; preset: enabled)
     Active: active (running) since Fri 2024-11-29 13:43:39 PST; 25min ago
   Main PID: 3559 (python3)
      Tasks: 4 (limit: 173)
        CPU: 3.599s
     CGroup: /system.slice/2mic_leds.service
             └─3559 /home/lvsatellite/wyoming-satellite/examples/.venv/bin/python3 2mic_service.py --uri tcp://127.0.0.1:10500`

This is my wyoming-satellite service config:

`[Unit]
Description=Wyoming Satellite
Wants=network-online.target
After=network-online.target
Requires=wyoming-openwakeword.service
Requires=2mic_leds.service

[Service]
Type=simple
ExecStart=/home/lvsatellite/wyoming-satellite/script/run \
    --name 'lvsatellite' \
    --uri 'tcp://0.0.0.0:10700' \
    --mic-command 'arecord -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
    --snd-command 'aplay -D plughw:CARD=seeed2micvoicec,DEV=0 -r 16000 -c 1 -f S16_LE -t raw' \
    --snd=command-rate 16000 \
    --snd-volume-multiplier 1 \
    --mic-auto-gain 5 \
    --mic-noise-suppression 2 \
    --wake-uri 'tcp://127.0.0.1:10400' \
    --wake-word-name 'ok_nabu' \
    --event-uri 'tcp://127.0.0.1:10500' \
    --awake-wav sounds/awake.wav \
    --done-wav sounds/done.wav

WorkingDirectory=/home/lvsatellite/wyoming-satellite
Restart=always
RestartSec=1

[Install]
WantedBy=default.target`

I did change it to ok_jarvis the first time I created the service but then quickly edited it back to ok_nabu and for some reason someone still thinks it's trying to be ok_jarvis.

**Comment by chezpaul** [comment]
You are correct. I got it working now. Thanks
