### ISSUE TITLE
ModuleNotFoundError: No module named 'wyoming_satellite.utils'

### ISSUE THREAD

**Issue by jenniferlee1818** [rhasspy/wyoming-satellite#49]
I'm having a hell of a time trying to get openwakeword + wyoming-mic-external and wyoming-satellite working as it should in docker.  I think I'm in over 16 hours of trying different things and sometimes it will work a few a times, but usually not at all.  I can't be of much help at this point because I haven't been able to figure out what I'm doing right when it does work correctly.  Seems like no rhyme or reason.

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/app/wyoming_satellite/__init__.py", line 2, in <module>
    from .satellite import (
  File "/app/wyoming_satellite/satellite.py", line 25, in <module>
    from .utils import DebugAudioWriter, multiply_volume, run_event_command, wav_to_events
ModuleNotFoundError: No module named 'wyoming_satellite.utils'

**Comment by preimmortal** [comment]
If you're using the docker container, then you'll need to fix the .dockerignore file.
I opened a PR to fix this along with a few other docker fixes: #50

**Comment by maxemoose** [comment]
Just encountered this issue as well. Thanks for the quick fix.
