### ISSUE TITLE
wyoming-event.service won't start, "No module named 'gpiozero'"

### ISSUE THREAD

**Issue by jerblack** [rhasspy/wyoming-satellite#68]
I have a Raspberry Pi runnign Raspbian lite 12 that I'm trying to setup as a Wyoming Satellite, and I used your TUI installer today to get it running. I am not using a Respeaker mic hat, I am using a USB conference puck. I do have a Hifiberry DAC as a HAT though because this Pi is also a Snapcast client. The reason I say that is because the error at startup is from a file named 2mic_service and it's trying to import a non existent gpiozero module.

```
Jan 18 18:02:48 callisto run_2mic[997]: Traceback (most recent call last):
Jan 18 18:02:48 callisto run_2mic[997]:   File "/home/jeremy/wyoming-satellite/examples/2mic_service.py", line 11, in <module>
Jan 18 18:02:48 callisto run_2mic[997]:     import gpiozero
Jan 18 18:02:48 callisto run_2mic[997]: ModuleNotFoundError: No module named 'gpiozero'
Jan 18 18:02:48 callisto run_2mic[996]: Traceback (most recent call last):
Jan 18 18:02:48 callisto run_2mic[996]:   File "/home/jeremy/wyoming-satellite/script/run_2mic", line 12, in <module>
Jan 18 18:02:48 callisto run_2mic[996]:     subprocess.check_call(
Jan 18 18:02:48 callisto run_2mic[996]:   File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
Jan 18 18:02:48 callisto run_2mic[996]:     raise CalledProcessError(retcode, cmd)
Jan 18 18:02:48 callisto run_2mic[996]: subprocess.CalledProcessError: Command '['/home/jeremy/wyoming-satellite/.venv/bin/python3', '/home/jeremy/wyoming-satellite/examples/2mic_service.py', '--uri', 'tcp://127.0.0.1:10500']' returned non-zero exit status 1.
Jan 18 18:02:48 callisto systemd[1]: wyoming-event.service: Main process exited, code=exited, status=1/FAILURE
```
If I `apt install python3-gpiozero` then the service starts. Shouldn't that have been installed in the venv you created though?

**Comment by llluis** [comment]
This service (and the gpiozero module) is only to control the leds in the respeaker 2mic module via spi. If you are not using this hat then you don’t need any of this.

**Comment by preimmortal** [comment]
It's also in the "optional" requirements file `requirements_respeaker.txt` which you should run the setup.py with if you need it

**Comment by jerblack** [comment]
Sorry, if I wasn't clear and I appreciate the setup advice, but I mainly posted the issue because I don't think this `wyoming-event.service` should have ever been installed by the automatic installer you get from running `python3 -m installer` unless the user selected an option other than `none` under Feedback > Respeaker > Event Service. The `wyoming-event.service` only runs `wyoming-satellite/script/run_2mic` to work with those Respeaker devices, so if you don't select the option saying you have that device, then you should have the service installed and erroring on startup.

**Comment by llluis** [comment]
Thanks for the clarification @jerblack, it’s a valid point.

**Comment by formatBCE** [comment]
Also, if user have chosen that feedback in automatic installer, why not install gpiozero? It's confusing. :)
