### ISSUE TITLE
No module named 'wyoming.ping'

### ISSUE THREAD

**Issue by KeithSBB** [rhasspy/wyoming-satellite#71]
I can find the module named 'wyoming.ping' to install anywhere. ??

```

9:37 PM
Failed to start wyoming-satellite.service - Wyoming Satellite.
systemd
9:37 PM
wyoming-satellite.service: Failed with result 'exit-code'.
systemd
9:37 PM
wyoming-satellite.service: Start request repeated too quickly.
systemd
9:37 PM
Stopped wyoming-satellite.service - Wyoming Satellite.
systemd
9:37 PM
wyoming-satellite.service: Scheduled restart job, restart counter is at 5.
systemd
9:37 PM
wyoming-satellite.service: Failed with result 'exit-code'.
systemd
9:37 PM
wyoming-satellite.service: Main process exited, code=exited, status=1/FAILURE
systemd
9:37 PM
subprocess.CalledProcessError: Command '['/home/mycroft/wyoming-satellite/.venv/bin/python3', '-m', 'wyoming_satellite', '--name', 'Bedroom smart speaker', '--uri', 'tcp://0.0.0.0:10700', '--mic-command', 'arecord -q -r 16000 -f S16_LE -c 1 -t raw -D plughw:CARD=JV601,DEV=0', '--snd-command', 'aplay -r 22050 -c 1 -f S16_LE -t raw', '--wake-uri', 'tcp://127.0.0.1:10400', '--wake-word-name', 'Alice', '--mic-auto-gain', '5', '--mic-noise-suppression', '2']' returned non-zero exit status 1.
run
9:37 PM
raise CalledProcessError(retcode, cmd)
run
9:37 PM
File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
run
9:37 PM
subprocess.check_call([context.env_exe, "-m", "wyoming_satellite"] + sys.argv[1:])
run
9:37 PM
File "/home/mycroft/wyoming-satellite/script/run", line 12, in <module>
run
9:37 PM
Traceback (most recent call last):
run

9:37 PM
ModuleNotFoundError: No module named 'wyoming.ping' 

run
9:37 PM
from wyoming.ping import Ping, Pong
run
9:37 PM
File "/home/mycroft/wyoming-satellite/wyoming_satellite/satellite.py", line 18, in <module>
run
9:37 PM
from .satellite import (
run
9:37 PM
File "/home/mycroft/wyoming-satellite/wyoming_satellite/__init__.py", line 4, in <module>
run
9:37 PM
File "<frozen runpy>", line 112, in _get_module_details
run
9:37 PM
File "<frozen runpy>", line 148, in _get_module_details
run
9:37 PM
File "<frozen runpy>", line 189, in _run_module_as_main
run
9:37 PM
Traceback (most recent call last):
run
9:37 PM
Started wyoming-satellite.service - Wyoming Satellite.
```

**Comment by llluis** [comment]
This looks like a duplicate of #59.
Is this a new install? What install method did you use?

In the `wyoming-satellite` dir, the command `.venv/bin/pip3 install 'wyoming==1.5.2` and a restart shall resolve.

**Comment by KeithSBB** [comment]
This was a result of "git pull origin master' on an existing manually setup wyoming-satellite (pre installer) which was working fine.   I tried running installer, but that didn't seem to work.  However, .venv/bin/pip3 install 'wyoming==1.5.2'
Fixed this issue for me,  Thanks
Adding some instructions in the README.md would benefit those who try to update their installations.
