### ISSUE TITLE
wyoming-satellite can't start up

### ISSUE THREAD

**Issue by pkkrusty** [rhasspy/wyoming-satellite#97]
I followed the 2MicHat guide and everything was working until I tried to upgrade to the commit where the ping problem was fixed. I did `.venv/bin/pip3 install --upgrade wyoming` which put 1.5.2 on my system, but then I got a warning:
```
wyoming-satellite 1.0.0 requires wyoming==1.4.1, but you have wyoming 1.5.2 which is incompatible.
```
And when I try to start wyoming-satellite, I get 
```
DEBUG:root:Namespace(mic_uri=None, mic_command='arecord -D plughw:CARD=CameraB409241,DEV=0 -r 16000 -c 1 -f S16_LE -t raw', mic_command_rate=16000, mic_command_width=2, mic_command_channels=1, mic_command_samples_per_chunk=1024, mic_volume_multiplier=1.0, mic_noise_suppression=0, mic_auto_gain=0, snd_uri=None, snd_command=None, snd_command_rate=22050, snd_command_width=2, snd_command_channels=1, snd_volume_multiplier=1.0, wake_uri='tcp://127.0.0.1:10400', wake_word_name=['jupiter'], wake_command=None, wake_command_rate=16000, wake_command_width=2, wake_command_channels=1, wake_refractory_seconds=3.0, vad=False, vad_threshold=0.5, vad_trigger_level=1, vad_buffer_seconds=2, vad_wake_word_timeout=5.0, event_uri=None, startup_command=None, detect_command=None, detection_command=None, transcript_command=None, stt_start_command=None, stt_stop_command=None, synthesize_command=None, tts_start_command=None, tts_stop_command=None, streaming_start_command=None, streaming_stop_command=None, error_command=None, connected_command=None, disconnected_command=None, awake_wav=None, done_wav=None, uri='tcp://0.0.0.0:10700', name='my satellite', area=None, no_zeroconf=False, zeroconf_name=None, zeroconf_host=None, debug_recording_dir=None, debug=True)
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/wyoming-satellite/wyoming_satellite/__main__.py", line 403, in <module>
    run()
  File "/home/pi/wyoming-satellite/wyoming_satellite/__main__.py", line 397, in run
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/wyoming-satellite/wyoming_satellite/__main__.py", line 277, in main
    satellite=Satellite(
TypeError: __init__() missing 1 required positional argument: 'version'
Traceback (most recent call last):
  File "/home/pi/wyoming-satellite/script/run", line 12, in <module>
    subprocess.check_call([context.env_exe, "-m", "wyoming_satellite"] + sys.argv[1:])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/pi/wyoming-satellite/.venv/bin/python3', '-m', 'wyoming_satellite', '--name', 'my satellite', '--uri', 'tcp://0.0.0.0:10700', '--mic-command', 'arecord -D plughw:CARD=CameraB409241,DEV=0 -r 16000 -c 1 -f S16_LE -t raw', '--wake-uri', 'tcp://127.0.0.1:10400', '--wake-word-name', 'jupiter', '--wake-refractory-seconds', '3', '--debug']' returned non-zero exit status 1.
```

**Comment by pkkrusty** [comment]
What's the command for that? Not familiar with selecting specific builds from GitHub (issue 60 was my first experience with it)

**Comment by llluis** [comment]
Yup, that's one way to do it too. :)

Next time you can run `git pull` in the `wyoming-satellite` folder to download the new version from github to your local installation folder.
